ARG BASE_IMAGE_TAG=latest

FROM ghcr.io/attocash/node:${BASE_IMAGE_TAG}

ARG APPLICATION_VERSION

ENV APPLICATION_VERSION=${APPLICATION_VERSION}

LABEL org.opencontainers.image.source https://github.com/attocash/node

ENV SPRING_PROFILES_ACTIVE=beta,json
