atto:
  node:
    voterStrategy: FORCE_ENABLED
    network: LOCAL
    publicAddress: localhost:${server.websocket.port}
  network:
    broadcaster:
      cache-expiration-time-in-seconds: 0

server:
  error:
    include-message: ALWAYS
    include-stacktrace: ALWAYS

logging:
  level:
    atto: TRACE
    atto.node.network: TRACE
    io.r2dbc.h2: INFO
    org.springframework.boot.autoconfigure: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
