spring:
  r2dbc:
    url: r2dbc:mysql://${ATTO_DB_HOST:localhost}:${ATTO_DB_PORT:3306}/${ATTO_DB_NAME:atto}
    username: ${ATTO_DB_USER:root}
    password: ${ATTO_DB_PASSWORD:}
  flyway:
    url: jdbc:mysql://${ATTO_DB_HOST:localhost}:${ATTO_DB_PORT:3306}/${ATTO_DB_NAME:atto}
    user: ${ATTO_DB_USER:root}
    password: ${ATTO_DB_PASSWORD:}

atto:
  node:
    voterStrategy: FORCE_ENABLED
    network: LOCAL
    public-uri: ws://localhost:${websocket.port}
  network:
    broadcaster:
      cache-expiration-time-in-seconds: 0

server:
  error:
    include-message: ALWAYS
    include-stacktrace: ALWAYS

logging:
  level:
    atto: INFO
    atto.node.network: INFO
    atto.node.transaction.TransactionService: DEBUG
    atto.node.transaction.priotization.TransactionPrioritizer: DEBUG
    io.r2dbc.h2: INFO
    org.springframework.boot.autoconfigure: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
