atto:
  node:
    network: BETA
  peer:
    defaultNodes:
      - node-adventurous.beta.core.atto.cash:8315
      - node-cautious.beta.core.atto.cash:8315
      - node-conservative.beta.core.atto.cash:8315
  transaction:
    genesis:
