spring:
  application:
    name: atto-node
    version: ${APPLICATION_VERSION:}
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
  webflux:
    format:
      date: iso
      time: iso
      date-time: iso
  r2dbc:
    url: r2dbc:mysql://${ATTO_DB_HOST}:${ATTO_DB_PORT:3306}/${ATTO_DB_NAME:atto}
    username: ${ATTO_DB_USER}
    password: ${ATTO_DB_PASSWORD}
    pool:
      min-idle: ${ATTO_DB_POOL_MIN_SIZE:1}
      max-size: ${ATTO_DB_POOL_MAX_SIZE:10}
      max-life-time: 8h
  flyway:
    url: jdbc:mysql://${ATTO_DB_HOST}:${ATTO_DB_PORT:3306}/${ATTO_DB_NAME:atto}
    user: ${ATTO_DB_USER}
    password: ${ATTO_DB_PASSWORD}

atto:
  use-x-forwarded-for: ${ATTO_USE_X_FORWARDED_FOR:false}
  signer:
    backend: ${ATTO_SIGNER_BACKEND:local}
    remote-url: ${ATTO_SIGNER_REMOTE_URL:}
    token: ${ATTO_SIGNER_REMOTE_TOKEN:}
    key: ${ATTO_PRIVATE_KEY:}
  node:
    force-historical: ${ATTO_NODE_FORCE_HISTORICAL:false}
    force-api: ${ATTO_NODE_FORCE_API:false}
    public-uri: ${ATTO_PUBLIC_URI}
  transaction:
    prioritization:
      frequency: 100
      group-max-size: 1_000
  vote:
    prioritization:
      frequency: 10
      group-max-size: 1_000
      cache-max-size: 20_000
    weight:
      minimal-rebroadcast-weight: 180_000_000_000_000_000 #180m
      minimal-confirmation-weight: 10_000_000_000_000_000_000 #10b
      confirmation-threshold: 65
      sample-period-in-days: 14
    election:
      expiring-after-time-in-seconds: 10
      expired-after-time-in-seconds: 30

springdoc:
  swagger-ui:
    path: /

logging:
  level:
    atto: INFO

server:
  port: 8080

websocket:
  port: 8082

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
      application-version: ${spring.application.version}
