atto:
  node:
    network: BETA
  peer:
    defaultNodes:
      - node-adventurous.beta.core.atto.cash
      - node-cautious.beta.core.atto.cash
      - node-conservative.beta.core.atto.cash
  transaction:
    genesis:
