spring:
  flyway:
    url: jdbc:h2:mem:${ATTO_DB_NAME:atto};MODE=MySQL;DB_CLOSE_DELAY=-1
    username:
    password:
  r2dbc:
    url: r2dbc:h2:mem:///${ATTO_DB_NAME:atto}

atto:
  db: H2
  node:
    voterStrategy: FORCE_ENABLED
    network: LOCAL
    publicAddress: localhost:${server.tcp.port}
  network:
    broadcaster:
      cache-expiration-time-in-seconds: 0

server:
  error:
    include-message: ALWAYS
    include-stacktrace: ALWAYS

logging:
  level:
    atto: TRACE
    atto.node.network: TRACE
    io.r2dbc.h2: INFO
    org.springframework.boot.autoconfigure: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
