package cash.atto.node

import com.sun.management.OperatingSystemMXBean
import io.github.oshai.kotlinlogging.KotlinLogging
import io.swagger.v3.oas.models.ExternalDocumentation
import io.swagger.v3.oas.models.OpenAPI
import io.swagger.v3.oas.models.info.Info
import jakarta.annotation.PostConstruct
import org.springframework.aot.hint.MemberCategory
import org.springframework.aot.hint.RuntimeHints
import org.springframework.aot.hint.RuntimeHintsRegistrar
import org.springframework.aot.hint.registerType
import org.springframework.boot.autoconfigure.AutoConfigureOrder
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.context.annotation.ImportRuntimeHints
import org.springframework.context.event.ApplicationEventMulticaster
import org.springframework.context.event.SimpleApplicationEventMulticaster
import org.springframework.core.env.Environment
import org.springframework.core.task.SimpleAsyncTaskExecutor
import org.springframework.scheduling.annotation.EnableScheduling

@ImportRuntimeHints(
    MicrometerWorkaround::class,
)
@Configuration
@EnableScheduling
@AutoConfigureOrder(0)
class ApplicationConfiguration {
    val logger = KotlinLogging.logger {}

    @PostConstruct
    fun init() {
        Thread.setDefaultUncaughtExceptionHandler { _, e ->
            logger.error(e) { "Uncaught on thread ${Thread.currentThread().name}" }
        }
    }

    @Bean
    fun applicationEventMulticaster(): ApplicationEventMulticaster {
        val multicaster = SimpleApplicationEventMulticaster()
        val executor = SimpleAsyncTaskExecutor("atto-event-")
        executor.setVirtualThreads(true)
        executor.concurrencyLimit = 16_384
        multicaster.setTaskExecutor(executor)
        multicaster.setErrorHandler {
            logger.error(it) { it.message }
        }
        return multicaster
    }

    @Bean
    fun openApi(environment: Environment): OpenAPI {
        val version = environment.getProperty("spring.application.version", "").ifEmpty { "dev" }
        return OpenAPI()
            .info(
                Info()
                    .title("Atto Node API")
                    .description(
                        "Reference Atto Node API endpoints and schemas for accounts, transactions, receivables and NDJSON streams.\n\n" +
                            "This specification is generated by this node build. Match its version to the node you integrate; " +
                            "publication and error behavior can differ between releases.\n\n" +
                            "Start with [node setup and configuration](https://atto.cash/docs/integration/node), " +
                            "or inspect public data in the [read-only API explorer](https://atto.cash/docs/tools/network).",
                    ).version(version),
            ).externalDocs(
                ExternalDocumentation()
                    .description("Node setup and configuration")
                    .url("https://atto.cash/docs/integration/node"),
            )
    }
}

class MicrometerWorkaround : RuntimeHintsRegistrar {
    override fun registerHints(
        hints: RuntimeHints,
        classLoader: ClassLoader?,
    ) {
        hints.reflection().registerType<OperatingSystemMXBean>(
            MemberCategory.INVOKE_PUBLIC_CONSTRUCTORS,
            MemberCategory.INVOKE_PUBLIC_METHODS,
        )
    }
}
