# Managed by management-terraform

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      NATIVE_IMAGE_OPTIONS: "--static --libc=musl --gc=G1 -R:MaxRAMPercentage=90"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: graalvm/setup-graalvm@0426e2e191540e8514dff98dc52a5f5146a2a276 # v1
        with:
          distribution: 'graalvm'
          java-version: '25'
          native-image-musl: true
          native-image-enable-sbom: true
          native-image-job-reports: true
          native-image-pr-reports: true
          native-image-pr-reports-update-existing: true
          cache: 'gradle'

      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6

      - run: ./gradlew --no-daemon nativeCompile

      - uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4

      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "BRANCH_NAME=${GITHUB_REF_NAME//\//_}" >> $GITHUB_ENV

      - uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7
        with:
          context: .
          pull: true
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ env.BRANCH_NAME }}
          build-args: |
            APPLICATION_VERSION=${{ github.sha }}
