on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: node
          path: ${{ github.workspace }}/build/libs

      - name: publish docker
        run: |
          echo $TOKEN | docker login ghcr.io -u rotilho --password-stdin
          
          docker build -t ghcr.io/attocash/node:${{ github.sha }} . --pull
          docker push ghcr.io/attocash/node:${{ github.sha }}
          
          BRANCH_NAME=${{ github.ref_name }}
          BRANCH_NAME=${BRANCH_NAME//\//_}
          
          docker tag ghcr.io/attocash/node:${{ github.sha }} ghcr.io/attocash/node:$BRANCH_NAME
          docker push ghcr.io/attocash/node:$BRANCH_NAME
        env:
          TOKEN: ${{ secrets.token }}