# Managed by management-terraform

name: Pull Request

on:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/test.yaml
  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    if: "!github.event.repository.private"
    uses: ./.github/workflows/codeql.yaml
