name: Pull Request
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.head.repo.fork == true
    uses: ./.github/workflows/build.yaml
  codeql:
    if: github.event.pull_request.head.repo.fork == true
    uses: ./.github/workflows/codeql.yaml
