# Managed by management-terraform

name: Pull Request

on:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        neighbour-mode:
          - classpath
          - live
    uses: ./.github/workflows/test.yaml
    with:
      neighbour_mode: ${{ matrix['neighbour-mode'] }}
