on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: tags
        run: git fetch --tags

      - name: release
        run: |
          echo $TOKEN | docker login ghcr.io -u rotilho --password-stdin
          
          RELEASE_BRANCH=$(echo "${{ github.ref_name }}" | sed 's/release\///')
          MAJOR_VERSION=$(echo "$RELEASE_BRANCH" | awk -F. '{print $1}')
          LATEST_TAG=$(git tag --list "v$MAJOR_VERSION.*" --sort=-v:refname | head -n1)
          
          if [ -z "$LATEST_TAG" ]; then
            MINOR=0
          else
            MINOR=$(( ${LATEST_TAG##*.} + 1 ))
          fi
          
          NEXT_TAG="$MAJOR_VERSION.$MINOR"
          
          docker pull ghcr.io/attocash/node:${{ github.sha }}
          docker tag ghcr.io/attocash/node:${{ github.sha }} ghcr.io/attocash/node:${NEXT_TAG}-${{ inputs.environment }}
          docker push ghcr.io/attocash/node:${NEXT_TAG}-${{ inputs.environment }}
          
          git tag v$NEXT_TAG
          git push origin v$NEXT_TAG
        env:
          TOKEN: ${{ secrets.token }}