name: Release Pipeline

on:
  push:
    branches:
      - 'release/[0-9]+.x'

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  codeql:
    uses: ./.github/workflows/codeql.yaml
  docker:
    needs:
      - build
      - codeql
    uses: ./.github/workflows/docker.yaml
    secrets:
      token: ${{ secrets.TOKEN }}
  dev:
    needs: [ docker ]
    uses: ./.github/workflows/release-environment.yaml
    with:
      environment: dev
    secrets:
      token: ${{ secrets.TOKEN }}
  beta:
    needs: [ dev ]
    uses: ./.github/workflows/release-environment.yaml
    with:
      environment: beta
    secrets:
      token: ${{ secrets.TOKEN }}
  live:
    needs: [ beta ]
    uses: ./.github/workflows/release-environment.yaml
    with:
      environment: live
    secrets:
      token: ${{ secrets.TOKEN }}

