# Managed by management-terraform

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      next-tag:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.image }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - run: git fetch --tags

      - uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4

      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: release
        run: |
          MAJOR_VERSION=$(echo "${{ inputs.next-tag }}" | awk -F. '{print $1}')
          SOURCE_IMAGE=ghcr.io/${{ github.repository }}:${{ github.sha }}-${{ inputs.image }}
          TARGET_IMAGE=ghcr.io/${{ github.repository }}

          echo TAG=${{ inputs.next-tag }} MAJOR_VERSION=${MAJOR_VERSION}

          docker buildx imagetools create \
            --tag "${TARGET_IMAGE}:${{ inputs.next-tag }}-${{ inputs.image }}" \
            --tag "${TARGET_IMAGE}:${MAJOR_VERSION}-${{ inputs.image }}" \
            "${SOURCE_IMAGE}"

          HIGHER_MAJOR_EXISTS=$(git tag --list 'v*' --sort=-v:refname | awk -F. '{print $1}' | sed 's/v//' | uniq | awk -v curr="$MAJOR_VERSION" '$1>curr {print "yes"; exit}')

          if [ "$HIGHER_MAJOR_EXISTS" != "yes" ]; then
            docker buildx imagetools create \
              --tag "${TARGET_IMAGE}:${{ inputs.image }}" \
              "${SOURCE_IMAGE}"
          fi
